### PR TITLE
latest live555

### LINKED ISSUE #68: ImpEncoder.cpp compile error
Building on Ubuntu:

```
% uname -a
Linux nuc10 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
% more /etc/debian_version
bullseye/sid
```

Compiling ImpEncoder.cpp via ./compile.sh results in:

```
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../toolchain/bin/mips-linux-gnu-g++   -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/v4l2wrapper/inc -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../live555/liveMedia/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../v4l2rtspserver-tools -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/filter -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/groupsock/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/liveMedia/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/UsageEnvironment/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/BasicUsageEnvironment/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../_install/include -I/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/freetype2/freetype2/include  -std=c++11 -Wall -O3 -g   -o CMakeFiles/v4l2rtspserver-master.dir/src/ImpEncoder.cpp.o -c /home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/src/ImpEncoder.cpp
In file included from /home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/src/HTTPServer.cpp:27:0:
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc/HTTPServer.h: In constructor 'HTTPServer::HTTPClientConnection::HTTPClientConnection(RTSPServer&, int, sockaddr_in)':
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc/HTTPServer.h:126:138: error: no matching function for call to 'RTSPServer::RTSPClientConnection::RTSPClientConnection(RTSPServer&, int&, sockaddr_in&)'
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc/HTTPServer.h:126:138: note: candidates are:
In file included from /home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/src/HTTPServer.cpp:19:0:
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/liveMedia/include/RTSPServer.hh:157:5: note: RTSPServer::RTSPClientConnection::RTSPClientConnection(RTSPServer&, int, const sockaddr_storage&)
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/liveMedia/include/RTSPServer.hh:157:5: note:   no known conversion for argument 3 from 'sockaddr_in' to 'const sockaddr_storage&'
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/liveMedia/include/RTSPServer.hh:135:9: note: RTSPServer::RTSPClientConnection::RTSPClientConnection(const RTSPServer::RTSPClientConnection&)
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/../Modules/live/live555/liveMedia/include/RTSPServer.hh:135:9: note:   candidate expects 1 argument, 3 provided
In file included from /home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/src/HTTPServer.cpp:27:0:
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc/HTTPServer.h: In static member function 'static HTTPServer* HTTPServer::createNew(UsageEnvironment&, Port, UserAuthenticationDatabase*, unsigned int, unsigned int, std::string)':
/home/cdknight/Dafang-Hacks-Main/v4l2rtspserver-master/inc/HTTPServer.h:154:48: error: no matching function for call to 'HTTPServer::setUpOurSocket(UsageEnvironment&, Port&)'
...
```

### PR DESCRIPTION
**Pull request by claud9999**
Closes #68 

So I have at least gotten the code to compile; I will test it tomorrow (consider this PR a "draft", it may be updated if I broke anything.) I am not 100% sure I understand the Live555 API changes and I'm really rusty on C++ so apologies if I've made a bone-headed mistake. I hope to test tomorrow on my cams.

Beyond updating the v4lrtspserver-master code, this adds the "current working version" of live555, which does not exist in an SCM so it's really wise that we maintain our own copy of what we understand so that the latest version doesn't change API's out from under us. This may also be true of other libraries that we rely on, particularly those that are not maintained in github or another public SCM repo.

### CODE REVIEW

**Comment by claud9999** [comment]
of course you can mostly ignore everything under the `Modules/live` folder (although you'd be wise to doublecheck it against the official release of live555, not that I introduced any backdoors or anything, but good to make it a habit to validate it.)

It *might* be worthwhile to have the compile script download the current official release and warn if it's newer than what we have in our repo. But live555 seems to change weekly so that might be annoying.

**Comment by nik0** [comment]
let's do like that !
Tell me when you tested ...

**Comment by claud9999** [comment]
Ok my testing uncovered one bug in my code, but otherwise it's looking good! Please consider merging into master.

**Comment by nik0** [comment]
Done
Thanks
Keep this project moving !! 👍🏻👍🏻

**Pull request merged**
