### PR TITLE
Fix 1080p on 64mb xiaofang

### PR DESCRIPTION
**Pull request by Yannik**
I have successfully tested this. Looking forward to reviews of this by other people.

### CODE REVIEW

**Review by nik0 — COMMENTED** [review]
What is the effect of poolsize to off and nrVBs to 2 ?

**Comment by Yannik** [comment]
These are values extracted from the stock `iCamera` binary using reverse-engineering.
The value currently used in Dafang-Hacks is from the SDK. It uses too much memory for 1080p to work.

**Comment by nik0** [comment]
Ok I will test on mine and eventually commit it

**Comment by Yannik** [comment]
Thanks!

**Comment by nik0** [comment]
@Yannik,
Do you know if on the stock firmware that use this "trick" there is motion detection ?
It seems that reducing the number of buffer  disable the motion ...

**Comment by Yannik** [comment]
I can only confirm that this fixes 1080p. I don't know about stock, because I've never used it. Also, I personally think motion in v4l2 is very unreliable so I only use motion in my zoneminder server with preclusive zones etc. Sorry that I can't comment on this further.

Are there multiple reports on this influencing motion detection?

**Pull request merged**
