### PR TITLE
Fix 69 remove system() calls on motion detection/tracking

### LINKED ISSUE #69: motion capture and performance of system()
The `system()` calls to `detectionOn.sh` and `detectionOff.sh` have huge performance impacts (process creation, particularly memory allocation, plus execution of a shell script...note the man page for system(), which states "The main cost of system() is inefficiency".) Motion capture is a time-critical component and I believe the system() call is causing significant loss of image/video data.

### PR DESCRIPTION
**Pull request by claud9999**
closes #69 

The detectionOn/Off/Tracking scripts should be re-written to be started as a daemon and watching the MQTT messages. Note that the mosquitto daemon should also be running on the camera for this to work. (v4lrtspserver should still function without the MQTT server, just no motion detection/tracking script execution.)

### CODE REVIEW

**Comment by claud9999** [comment]
sorry probably should have made the other PR a branch as well...merge #72 before merging this'n.

**Comment by claud9999** [comment]
also I don't know how to release updated detectionOn/Off/Track scripts to use mqtt and scripts/configs to start/stop the MQTT server...

**Comment by jmtatsch** [comment]
So basically now we would need a mqtt listener that watches for motion events and then executes detectionOn/Off.sh?

**Comment by claud9999** [comment]
Yeah I have such a script, am debugging it but having trouble restarting the RTSP server. Hope to have a solution early next week or possibly later today. I'm thinking, now that I see that the server uses shared memory for its configuration, I might switch to communicating via shared memory instead of MQTT and adding a command to support triggering shell scripts.

**Comment by claud9999** [comment]
So I have a new PR here with some fixes and it works great with MQTT (once I fixed my bug.) Where should I put the script? (I basically made `detectionOn.sh` and `detectionOff.sh` functions inside `mqtt-detection.sh`.) I also need to add control scripts for the mosquitto broker and UI controls as well.

**Comment by claud9999** [comment]
The scripts and changes are committed to a branch in my fork: https://github.com/claud9999/Xiaomi-Dafang-Hacks/tree/mqtt_detection

I will submit a ticket to Dafang-Hacks and a PR soon after.

**Pull request merged**
